### ISSUE TITLE
Considered gopkg? 

### ISSUE THREAD

**Issue by karalabe** [jmcvetta/napping#21]
Hey,

  I've just found your code while looking for a rest api client base for implementing access to a few services I'd like to use. However, I was wondering whether you'd consider versioning your lib through http://gopkg.in? In essence it would mean rewriting your import paths to gopkg.in/jmcvetta/napping.v1, with gopkg mapping your versioned paths to individual github branches. The advantage would be some API compatibility guarantee (i.e. you can bump the version if a change is incompatible, and don't break everyone's code :) ).

E.g. My [Iris client](https://github.com/project-iris/iris-go) uses such a scheme and it's nice to be able to sleep well at night even after major updates :)

**Comment by jmcvetta** [comment]
Import paths in examples updated and merged in 3c60a1e79e195e0861980999ba4a39cc9f0418c2
