### ISSUE TITLE
Why use Params map instead of just url.Values?

### ISSUE THREAD

**Issue by cameront** [jmcvetta/napping#24]
I need to set multiple values for a single parameter key, which url values permits since the map value is an array, but napping.Params is a map of string->string.

Would you be opposed to a change making params values an array?

**Comment by gdm85** [comment]
I also think it should be URL Values

**Comment by jmcvetta** [comment]
This seems like a reasonable idea.  If you would like to contribute a PR implementing it, I will be happy to accept it.
