### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>

### ISSUE THREAD

**Issue by starJammer** [jmcvetta/napping#28]
Hey jmcvetta,

did you ever encounter this error message during the development of this library?

"Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>

I'm curious because I'm running into this now but using a separate library I made inspired by yours. Not sure if I'm doing something wrong. Well, I appreciate the help. Thank you.

**Comment by jmcvetta** [comment]
Hi @starJammer,

No, I've never encountered that error message.  My *guess* is that it's caused by a bug in the host you're connecting to, or by malicious network activity.  


Cheers,

J
